/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RECF Manuals Public API
 * Read-only, public JSON API for RECF program manuals and Q&A. No authentication is required; requests are rate limited by IP and responses are cacheable.
 * OpenAPI spec version: 1.0.0
 */
import type { Error, GetProgram200, ListPrograms200 } from "../recf-manuals-public-api.schemas";

export type listProgramsResponse200 = {
	data: ListPrograms200;
	status: 200;
};

export type listProgramsResponseSuccess = listProgramsResponse200 & {
	headers: Headers;
};

export type listProgramsResponse = listProgramsResponseSuccess;

export const getListProgramsUrl = () => {
	return `https://games.recf.org/api/v1/programs`;
};

/**
 * @summary List programs
 */
export const listPrograms = async (options?: RequestInit): Promise<listProgramsResponse> => {
	const res = await fetch(getListProgramsUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: listProgramsResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as listProgramsResponse;
};

export type getProgramResponse200 = {
	data: GetProgram200;
	status: 200;
};

export type getProgramResponse404 = {
	data: Error;
	status: 404;
};

export type getProgramResponseSuccess = getProgramResponse200 & {
	headers: Headers;
};
export type getProgramResponseError = getProgramResponse404 & {
	headers: Headers;
};

export type getProgramResponse = getProgramResponseSuccess | getProgramResponseError;

export const getGetProgramUrl = (slug: string) => {
	return `https://games.recf.org/api/v1/programs/${slug}`;
};

/**
 * @summary Get program detail
 */
export const getProgram = async (
	slug: string,
	options?: RequestInit,
): Promise<getProgramResponse> => {
	const res = await fetch(getGetProgramUrl(slug), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getProgramResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as getProgramResponse;
};
