/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RECF Manuals Public API
 * Read-only, public JSON API for RECF program manuals and Q&A. No authentication is required; requests are rate limited by IP and responses are cacheable.
 * OpenAPI spec version: 1.0.0
 */
import type { GetOpenApiSpec200 } from "../recf-manuals-public-api.schemas";

export type getOpenApiSpecResponse200 = {
	data: GetOpenApiSpec200;
	status: 200;
};

export type getOpenApiSpecResponseSuccess = getOpenApiSpecResponse200 & {
	headers: Headers;
};

export type getOpenApiSpecResponse = getOpenApiSpecResponseSuccess;

export const getGetOpenApiSpecUrl = () => {
	return `https://games.recf.org/api/v1/openapi.json/openapi.json`;
};

/**
 * @summary This OpenAPI 3.1 document
 */
export const getOpenApiSpec = async (options?: RequestInit): Promise<getOpenApiSpecResponse> => {
	const res = await fetch(getGetOpenApiSpecUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getOpenApiSpecResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as getOpenApiSpecResponse;
};
