/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RECF Manuals Public API
 * Read-only, public JSON API for RECF program manuals and Q&A. No authentication is required; requests are rate limited by IP and responses are cacheable.
 * OpenAPI spec version: 1.0.0
 */
import type {
	Error,
	ExportManualPdfParams,
	GetChangelog200,
	GetDefinition200,
	GetManual200,
	GetManualBundle200,
	GetRule200,
	SearchManual200,
	SearchManualParams,
} from "../recf-manuals-public-api.schemas";

export type getLatestManualResponse307 = {
	data: void;
	status: 307;
};

export type getLatestManualResponse404 = {
	data: Error;
	status: 404;
};
export type getLatestManualResponseError = (
	| getLatestManualResponse307
	| getLatestManualResponse404
) & {
	headers: Headers;
};

export type getLatestManualResponse = getLatestManualResponseError;

export const getGetLatestManualUrl = (slug: string) => {
	return `https://games.recf.org/api/v1/openapi.json/programs/${slug}/manual`;
};

/**
 * @summary Redirect to the latest manual version
 */
export const getLatestManual = async (
	slug: string,
	options?: RequestInit,
): Promise<getLatestManualResponse> => {
	const res = await fetch(getGetLatestManualUrl(slug), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getLatestManualResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as getLatestManualResponse;
};

export type getManualResponse200 = {
	data: GetManual200;
	status: 200;
};

export type getManualResponse404 = {
	data: Error;
	status: 404;
};

export type getManualResponseSuccess = getManualResponse200 & {
	headers: Headers;
};
export type getManualResponseError = getManualResponse404 & {
	headers: Headers;
};

export type getManualResponse = getManualResponseSuccess | getManualResponseError;

export const getGetManualUrl = (slug: string, version: string) => {
	return `https://games.recf.org/api/v1/openapi.json/programs/${slug}/manual/${version}`;
};

/**
 * @summary Get the full manual for a version
 */
export const getManual = async (
	slug: string,
	version: string,
	options?: RequestInit,
): Promise<getManualResponse> => {
	const res = await fetch(getGetManualUrl(slug, version), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getManualResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as getManualResponse;
};

export type getManualBundleResponse200 = {
	data: GetManualBundle200;
	status: 200;
};

export type getManualBundleResponse404 = {
	data: Error;
	status: 404;
};

export type getManualBundleResponseSuccess = getManualBundleResponse200 & {
	headers: Headers;
};
export type getManualBundleResponseError = getManualBundleResponse404 & {
	headers: Headers;
};

export type getManualBundleResponse = getManualBundleResponseSuccess | getManualBundleResponseError;

export const getGetManualBundleUrl = (slug: string, version: string) => {
	return `https://games.recf.org/api/v1/openapi.json/programs/${slug}/manual/${version}/bundle`;
};

/**
 * @summary Offline bundle: manual content + Q&A + hash
 */
export const getManualBundle = async (
	slug: string,
	version: string,
	options?: RequestInit,
): Promise<getManualBundleResponse> => {
	const res = await fetch(getGetManualBundleUrl(slug, version), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getManualBundleResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as getManualBundleResponse;
};

export type getChangelogResponse200 = {
	data: GetChangelog200;
	status: 200;
};

export type getChangelogResponse404 = {
	data: Error;
	status: 404;
};

export type getChangelogResponseSuccess = getChangelogResponse200 & {
	headers: Headers;
};
export type getChangelogResponseError = getChangelogResponse404 & {
	headers: Headers;
};

export type getChangelogResponse = getChangelogResponseSuccess | getChangelogResponseError;

export const getGetChangelogUrl = (slug: string, version: string) => {
	return `https://games.recf.org/api/v1/openapi.json/programs/${slug}/manual/${version}/changelog`;
};

/**
 * @summary Changelog up to and including a version
 */
export const getChangelog = async (
	slug: string,
	version: string,
	options?: RequestInit,
): Promise<getChangelogResponse> => {
	const res = await fetch(getGetChangelogUrl(slug, version), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getChangelogResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as getChangelogResponse;
};

export type searchManualResponse200 = {
	data: SearchManual200;
	status: 200;
};

export type searchManualResponse404 = {
	data: Error;
	status: 404;
};

export type searchManualResponseSuccess = searchManualResponse200 & {
	headers: Headers;
};
export type searchManualResponseError = searchManualResponse404 & {
	headers: Headers;
};

export type searchManualResponse = searchManualResponseSuccess | searchManualResponseError;

export const getSearchManualUrl = (slug: string, version: string, params?: SearchManualParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `https://games.recf.org/api/v1/openapi.json/programs/${slug}/manual/${version}/search?${stringifiedParams}`
		: `https://games.recf.org/api/v1/openapi.json/programs/${slug}/manual/${version}/search`;
};

/**
 * @summary Full-text rule search
 */
export const searchManual = async (
	slug: string,
	version: string,
	params?: SearchManualParams,
	options?: RequestInit,
): Promise<searchManualResponse> => {
	const res = await fetch(getSearchManualUrl(slug, version, params), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: searchManualResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as searchManualResponse;
};

export type exportManualPdfResponse200 = {
	data: Blob;
	status: 200;
};

export type exportManualPdfResponse404 = {
	data: Error;
	status: 404;
};

export type exportManualPdfResponseSuccess = exportManualPdfResponse200 & {
	headers: Headers;
};
export type exportManualPdfResponseError = exportManualPdfResponse404 & {
	headers: Headers;
};

export type exportManualPdfResponse = exportManualPdfResponseSuccess | exportManualPdfResponseError;

export const getExportManualPdfUrl = (
	slug: string,
	version: string,
	params?: ExportManualPdfParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `https://games.recf.org/api/v1/openapi.json/programs/${slug}/manual/${version}/export.pdf?${stringifiedParams}`
		: `https://games.recf.org/api/v1/openapi.json/programs/${slug}/manual/${version}/export.pdf`;
};

/**
 * @summary Export the manual as a PDF
 */
export const exportManualPdf = async (
	slug: string,
	version: string,
	params?: ExportManualPdfParams,
	options?: RequestInit,
): Promise<exportManualPdfResponse> => {
	const res = await fetch(getExportManualPdfUrl(slug, version, params), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.blob();
	const data: exportManualPdfResponse["data"] = body as exportManualPdfResponse["data"];
	return { data, status: res.status, headers: res.headers } as exportManualPdfResponse;
};

export type getRuleResponse200 = {
	data: GetRule200;
	status: 200;
};

export type getRuleResponse404 = {
	data: Error;
	status: 404;
};

export type getRuleResponseSuccess = getRuleResponse200 & {
	headers: Headers;
};
export type getRuleResponseError = getRuleResponse404 & {
	headers: Headers;
};

export type getRuleResponse = getRuleResponseSuccess | getRuleResponseError;

export const getGetRuleUrl = (slug: string, version: string, stableKey: string) => {
	return `https://games.recf.org/api/v1/openapi.json/programs/${slug}/manual/${version}/rules/${stableKey}`;
};

/**
 * @summary Get a single rule
 */
export const getRule = async (
	slug: string,
	version: string,
	stableKey: string,
	options?: RequestInit,
): Promise<getRuleResponse> => {
	const res = await fetch(getGetRuleUrl(slug, version, stableKey), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getRuleResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as getRuleResponse;
};

export type getDefinitionResponse200 = {
	data: GetDefinition200;
	status: 200;
};

export type getDefinitionResponse404 = {
	data: Error;
	status: 404;
};

export type getDefinitionResponseSuccess = getDefinitionResponse200 & {
	headers: Headers;
};
export type getDefinitionResponseError = getDefinitionResponse404 & {
	headers: Headers;
};

export type getDefinitionResponse = getDefinitionResponseSuccess | getDefinitionResponseError;

export const getGetDefinitionUrl = (slug: string, version: string, stableKey: string) => {
	return `https://games.recf.org/api/v1/openapi.json/programs/${slug}/manual/${version}/definitions/${stableKey}`;
};

/**
 * @summary Get a single definition
 */
export const getDefinition = async (
	slug: string,
	version: string,
	stableKey: string,
	options?: RequestInit,
): Promise<getDefinitionResponse> => {
	const res = await fetch(getGetDefinitionUrl(slug, version, stableKey), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getDefinitionResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as getDefinitionResponse;
};
