/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RECF Manuals Public API
 * Read-only, public JSON API for RECF program manuals and Q&A. No authentication is required; requests are rate limited by IP and responses are cacheable.
 * OpenAPI spec version: 1.0.0
 */
import type {
	Error,
	GetQa200,
	ListQa200,
	ListQaParams,
	ListRuleQa200,
	ListRuleQaParams,
} from "../recf-manuals-public-api.schemas";

export type listQaResponse200 = {
	data: ListQa200;
	status: 200;
};

export type listQaResponse404 = {
	data: Error;
	status: 404;
};

export type listQaResponseSuccess = listQaResponse200 & {
	headers: Headers;
};
export type listQaResponseError = listQaResponse404 & {
	headers: Headers;
};

export type listQaResponse = listQaResponseSuccess | listQaResponseError;

export const getListQaUrl = (slug: string, params?: ListQaParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `https://games.recf.org/api/v1/programs/${slug}/qa?${stringifiedParams}`
		: `https://games.recf.org/api/v1/programs/${slug}/qa`;
};

/**
 * @summary List published Q&A for a program
 */
export const listQa = async (
	slug: string,
	params?: ListQaParams,
	options?: RequestInit,
): Promise<listQaResponse> => {
	const res = await fetch(getListQaUrl(slug, params), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: listQaResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as listQaResponse;
};

export type getQaResponse200 = {
	data: GetQa200;
	status: 200;
};

export type getQaResponse404 = {
	data: Error;
	status: 404;
};

export type getQaResponseSuccess = getQaResponse200 & {
	headers: Headers;
};
export type getQaResponseError = getQaResponse404 & {
	headers: Headers;
};

export type getQaResponse = getQaResponseSuccess | getQaResponseError;

export const getGetQaUrl = (slug: string, qnaNumber: string) => {
	return `https://games.recf.org/api/v1/programs/${slug}/qa/${qnaNumber}`;
};

/**
 * @summary Get a single Q&A entry
 */
export const getQa = async (
	slug: string,
	qnaNumber: string,
	options?: RequestInit,
): Promise<getQaResponse> => {
	const res = await fetch(getGetQaUrl(slug, qnaNumber), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getQaResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as getQaResponse;
};

export type getQaRssResponse200 = {
	data: string;
	status: 200;
};

export type getQaRssResponse404 = {
	data: Error;
	status: 404;
};

export type getQaRssResponseSuccess = getQaRssResponse200 & {
	headers: Headers;
};
export type getQaRssResponseError = getQaRssResponse404 & {
	headers: Headers;
};

export type getQaRssResponse = getQaRssResponseSuccess | getQaRssResponseError;

export const getGetQaRssUrl = (slug: string) => {
	return `https://games.recf.org/api/v1/programs/${slug}/qa.rss`;
};

/**
 * @summary RSS 2.0 feed of the latest published Q&A
 */
export const getQaRss = async (slug: string, options?: RequestInit): Promise<getQaRssResponse> => {
	const res = await fetch(getGetQaRssUrl(slug), {
		...options,
		method: "GET",
	});

	const contentType = (res.headers.get("content-type") ?? "").toLowerCase();
	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getQaRssResponse["data"] = body
		? contentType.includes("json")
			? JSON.parse(body)
			: body
		: {};
	return { data, status: res.status, headers: res.headers } as getQaRssResponse;
};

export type listRuleQaResponse200 = {
	data: ListRuleQa200;
	status: 200;
};

export type listRuleQaResponse404 = {
	data: Error;
	status: 404;
};

export type listRuleQaResponseSuccess = listRuleQaResponse200 & {
	headers: Headers;
};
export type listRuleQaResponseError = listRuleQaResponse404 & {
	headers: Headers;
};

export type listRuleQaResponse = listRuleQaResponseSuccess | listRuleQaResponseError;

export const getListRuleQaUrl = (slug: string, stableKey: string, params?: ListRuleQaParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `https://games.recf.org/api/v1/programs/${slug}/rules/${stableKey}/qa?${stringifiedParams}`
		: `https://games.recf.org/api/v1/programs/${slug}/rules/${stableKey}/qa`;
};

/**
 * @summary List Q&A targeting a specific rule
 */
export const listRuleQa = async (
	slug: string,
	stableKey: string,
	params?: ListRuleQaParams,
	options?: RequestInit,
): Promise<listRuleQaResponse> => {
	const res = await fetch(getListRuleQaUrl(slug, stableKey, params), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: listRuleQaResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as listRuleQaResponse;
};
