/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * RECF Manuals Public API
 * Read-only, public JSON API for RECF program manuals and Q&A. No authentication is required; requests are rate limited by IP and responses are cacheable.
 * OpenAPI spec version: 1.0.0
 */
export interface Meta {
	version?: string;
	timestamp?: string;
}

export type ErrorError = {
	message?: string;
	code?: string;
};

export interface Error {
	error?: ErrorError;
	meta?: Meta;
}

/**
 * @nullable
 */
export type AuthorAudienceRole =
	| (typeof AuthorAudienceRole)[keyof typeof AuthorAudienceRole]
	| null;

export const AuthorAudienceRole = {
	student: "student",
	coach: "coach",
	event_partner: "event_partner",
	volunteer: "volunteer",
	other: "other",
} as const;

/**
 * Publicly-visible submitter identity.
 */
export interface Author {
	username: string;
	/** @nullable */
	audienceRole: AuthorAudienceRole;
}

/**
 * Rich-text block content.
 */
export type AnswerBody = { [key: string]: unknown };

export interface Answer {
	id?: string;
	/** Rich-text block content. */
	body?: AnswerBody;
	isBinding?: boolean;
	/** @nullable */
	publishedAt?: string | null;
}

export type QuestionListItemStatus =
	(typeof QuestionListItemStatus)[keyof typeof QuestionListItemStatus];

export const QuestionListItemStatus = {
	published: "published",
	answered: "answered",
} as const;

export interface QuestionListItem {
	id?: string;
	qnaNumber?: number;
	subject?: string;
	targetRuleStableKey?: string;
	ruleLabel?: string;
	tags?: string[];
	status?: QuestionListItemStatus;
	submittedAt?: string;
	/** @nullable */
	answeredAt?: string | null;
	hasAnswer?: boolean;
	askedBy?: Author;
}

/**
 * Rich-text block content.
 */
export type QuestionDetailBody = { [key: string]: unknown };

export type QuestionDetailStatus = (typeof QuestionDetailStatus)[keyof typeof QuestionDetailStatus];

export const QuestionDetailStatus = {
	published: "published",
	answered: "answered",
} as const;

export type QuestionDetailSeason = {
	slug?: string;
	name?: string;
};

export interface QuestionDetail {
	id?: string;
	qnaNumber?: number;
	subject?: string;
	/** Rich-text block content. */
	body?: QuestionDetailBody;
	targetRuleStableKey?: string;
	ruleLabel?: string;
	tags?: string[];
	status?: QuestionDetailStatus;
	submittedAt?: string;
	/** @nullable */
	answeredAt?: string | null;
	askedBy?: Author;
	season?: QuestionDetailSeason;
	answer?: Answer | null;
}

export interface Pagination {
	total?: number;
	limit?: number;
	offset?: number;
}

export interface Revision {
	versionLabel?: string;
	/** @nullable */
	publishedAt?: string | null;
	/** @nullable */
	releasedDateLabel?: string | null;
}

export interface ProgramListItem {
	id?: string;
	slug?: string;
	name?: string;
	/** @nullable */
	currentVersionLabel?: string | null;
	/** @nullable */
	qnaUrl?: string | null;
}

export interface ProgramDetail {
	id?: string;
	slug?: string;
	name?: string;
	shortName?: string;
	description?: string;
	/** @nullable */
	coverImage?: string | null;
	/** @nullable */
	defaultQnaUrl?: string | null;
	revisions?: Revision[];
}

export type ListPrograms200 = {
	data: ProgramListItem[];
	meta: Meta;
};

export type GetProgram200 = {
	data: ProgramDetail;
	meta: Meta;
};

export type GetManual200Data = { [key: string]: unknown };

export type GetManual200 = {
	data: GetManual200Data;
	meta: Meta;
};

export type GetManualBundle200Data = { [key: string]: unknown };

export type GetManualBundle200 = {
	data: GetManualBundle200Data;
	meta: Meta;
};

export type GetChangelog200DataEntriesItem = { [key: string]: unknown };

export type GetChangelog200Data = {
	revisionVersion?: string;
	entries?: GetChangelog200DataEntriesItem[];
};

export type GetChangelog200 = {
	data: GetChangelog200Data;
	meta: Meta;
};

export type SearchManualParams = {
	/**
	 * Search query (1–200 chars).
	 * @minLength 1
	 * @maxLength 200
	 */
	q?: string;
	/**
	 * Results per page (1–100).
	 * @minimum 1
	 * @maximum 100
	 */
	limit?: number;
	/**
	 * Pagination offset.
	 * @minimum 0
	 */
	offset?: number;
};

export type SearchManual200ResultsItem = { [key: string]: unknown };

export type SearchManual200 = {
	results?: SearchManual200ResultsItem[];
	total?: number;
	limit?: number;
	offset?: number;
};

export type ExportManualPdfParams = {
	/**
	 * light or dark.
	 */
	theme?: ExportManualPdfTheme;
	/**
	 * letter or a4.
	 */
	paperSize?: ExportManualPdfPaperSize;
	/**
	 * Include Q&A.
	 */
	includeQa?: boolean;
	/**
	 * Show revision marks.
	 */
	revisionMarks?: boolean;
	/**
	 * Include cover art.
	 */
	coverArt?: boolean;
};

export type ExportManualPdfTheme = (typeof ExportManualPdfTheme)[keyof typeof ExportManualPdfTheme];

export const ExportManualPdfTheme = {
	light: "light",
	dark: "dark",
} as const;

export type ExportManualPdfPaperSize =
	(typeof ExportManualPdfPaperSize)[keyof typeof ExportManualPdfPaperSize];

export const ExportManualPdfPaperSize = {
	letter: "letter",
	a4: "a4",
} as const;

export type GetRule200Data = { [key: string]: unknown };

export type GetRule200 = {
	data: GetRule200Data;
	meta: Meta;
};

export type GetDefinition200Data = { [key: string]: unknown };

export type GetDefinition200 = {
	data: GetDefinition200Data;
	meta: Meta;
};

export type ListQaParams = {
	/**
	 * Filter by targeted rule key.
	 */
	ruleStableKey?: string;
	/**
	 * Filter by tag.
	 */
	tag?: string;
	/**
	 * published or answered.
	 */
	status?: ListQaStatus;
	/**
	 * Results per page (1–100).
	 * @minimum 1
	 * @maximum 100
	 */
	limit?: number;
	/**
	 * Pagination offset.
	 * @minimum 0
	 */
	offset?: number;
};

export type ListQaStatus = (typeof ListQaStatus)[keyof typeof ListQaStatus];

export const ListQaStatus = {
	published: "published",
	answered: "answered",
} as const;

export type ListQa200Data = {
	questions?: QuestionListItem[];
	pagination?: Pagination;
};

export type ListQa200 = {
	data: ListQa200Data;
	meta: Meta;
};

export type GetQa200 = {
	data: QuestionDetail;
	meta: Meta;
};

export type ListRuleQaParams = {
	/**
	 * Results per page (1–100).
	 * @minimum 1
	 * @maximum 100
	 */
	limit?: number;
	/**
	 * Pagination offset.
	 * @minimum 0
	 */
	offset?: number;
};

export type ListRuleQa200Data = {
	ruleStableKey?: string;
	questions?: QuestionListItem[];
	pagination?: Pagination;
};

export type ListRuleQa200 = {
	data: ListRuleQa200Data;
	meta: Meta;
};

export type GetOpenApiSpec200 = { [key: string]: unknown };
